accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

brochure/urls.py
from django.urls import path

from . import views

app_name = 'brochure'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('brochure.urls', namespace='brochure')),
    path('icecream/', include('ice_cream.urls', namespace='ice_cream')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

ice_cream/urls.py
from django.urls import path

from . import views

app_name = 'ice_cream'

urlpatterns = [
    path('<int:pk>/delete/', views.delete_view, name='delete'),
    path('new/', views.CreateView.as_view(), name='ice_cream_new'),
    path('<int:pk>/', views.increment_likes, name='increment_likes'),
    path('<str:selection>/', views.IndexView.as_view(), name='selection'),
    path('', views.IndexView.as_view(), name='index'),
]

accounts/models.py
from django.db import models

# Create your models here.

brochure/models.py
from django.db import models

# Create your models here.

ice_cream/models.py
from django.db import models
from datetime import date
from django.urls import reverse

class IceCream(models.Model):

    CHOCOLATE = 'CHOCOLATE'
    VANILLA = 'VANILLA'

    WEEKLY = 'WEEKLY'
    DAILY = 'DAILY'
    SEASONAL = 'SEASONAL'

    AVAILABLE_CHOICES = [
        (WEEKLY, 'Weekly'),
        (DAILY, 'Daily'),
        (SEASONAL, 'Seasonal'),
    ]

    BASE_CHOICES = [
        (CHOCOLATE, 'Chocolate'),
        (VANILLA, 'Vanilla'),
    ]

    flavor = models.CharField(max_length=255)
    available = models.CharField(max_length=255, choices=AVAILABLE_CHOICES)
    base = models.CharField(max_length=255, choices=BASE_CHOICES)
    featured = models.BooleanField(default=False)
    churn_date = models.DateField('date churned', default=date.today)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.flavor

    def get_absolute_url(self):
        return reverse('ice_cream:index')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

brochure/views.py
from django.shortcuts import render
from django.views import generic

class IndexView(generic.TemplateView):
    template_name = 'brochure/index.html'

class AboutView(generic.TemplateView):
    template_name = 'brochure/about.html'

ice_cream/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import IceCream

def is_superuser_check(user):
    return user.is_superuser

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'ice_cream/index.html'

    def get_queryset(self):
        if 'selection' in self.kwargs:
            return IceCream.objects.filter(available = self.kwargs['selection'].upper())
        return IceCream.objects.all()

class CreateView(UserPassesTestMixin, generic.CreateView):
    model = IceCream
    template_name = 'ice_cream/ice_cream_new.html'
    fields = '__all__'

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return redirect('ice_cream:index')

@user_passes_test(is_superuser_check)
def delete_view(request, pk):
    ice_cream = get_object_or_404(IceCream, pk=pk)
    ice_cream.delete()
    return HttpResponseRedirect(reverse_lazy('ice_cream:index'))

def increment_likes(request, pk):
    ice_cream = get_object_or_404(IceCream, pk=pk)
    ice_cream.likes += 1
    ice_cream.save()
    return HttpResponseRedirect(reverse('ice_cream:index'))

accounts/templates/signup.html
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button>Sign up</button>
</form>

brochure/templates/brochure/about.html
{% extends 'brochure/base.html' %}

{% block content %}
<div>I am the about!</div>
{% endblock content %}

brochure/templates/brochure/base.html
{% load static %}
<html>
  <head>
    <title>Buster's Ice Cream Shoppe</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/base.css' %}">
  </head>
  <body>
    {% include 'brochure/header.html' %}
    {% block content %}
    {% endblock content%}
    {% include 'brochure/footer.html' %}
  </body>
</html>

brochure/templates/brochure/footer.html
{% block footer %}
<h1>I am the footer</h1>
{% endblock footer %}

brochure/templates/brochure/header.html
{% block header %}
<ul>
  <li><a href="{% url 'brochure:index' %}">Home</a></li>
  <li><a href="{% url 'brochure:about' %}">About</a></li>
  <li><a href="{% url 'ice_cream:index' %}">Flavors</a></li>
  {% if user.is_authenticated %}
  <li><a href="{% url 'logout' %}">Logout</a></li>
  {% endif %}
</ul>
{% endblock header %}

brochure/templates/brochure/index.html
{% extends 'brochure/base.html' %}

{% block content %}
  <h1>Hey there! This is the home page!</h1>
{% endblock content%}

ice_cream/templates/ice_cream/header.html
<ul>
  <li><a href="{% url 'ice_cream:selection' 'daily' %}">Daily</a></li>
  <li><a href="{% url 'ice_cream:selection' 'weekly' %}">Weekly</a></li>
  <li><a href="{% url 'ice_cream:selection' 'seasonal' %}">Seasonal</a></li>
</ul>

ice_cream/templates/ice_cream/ice_cream_new.html
<h2>Add a New Ice Cream</h2>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button>Add new</button>
</form>

ice_cream/templates/ice_cream/index.html
{% extends 'brochure/base.html' %}
{% block content %}
{% include 'ice_cream/header.html' %}
{% for object in object_list %}
  <form action='{% url 'ice_cream:increment_likes' object.id %}' method='post'>
    {% csrf_token %}
    <div>
      <p>{{object.flavor}}</p>
      <button name=>+<span>{{object.likes}}</span></button>
      {% if request.user.is_superuser %}
      <a href="{% url 'ice_cream:delete' object.id %}">Delete</a>
      {% endif %}
    </div>
  </form>
{% endfor %}
{% endblock %}